### ISSUE TITLE
The usage of the @filename API for file uploading is deprecated - File upload

### ISSUE THREAD

**Issue by ghost** [podio-community/podio-php#74] opened 2014-12-03 15:05 UTC
Line 179: Lib/Podio.php throws an error when calling it as suggested in documentation:
http://podio.github.io/podio-php/api-requests/

curl_setopt(): The usage of the @filename API for file uploading is deprecated. Please use the CURLFile class instead 

If you either remove the @ from the filename, it seems to work successfully... or if you create a CURLFile object like so:

```
      // Create a CURLFile object
      $cfile = curl_file_create( $attributes[ "source" ] );

      // Assign POST data
      $data[ $attributes[ "filename" ] ] = $cfile;
      curl_setopt(self::$ch, CURLOPT_POST,1);
      curl_setopt(self::$ch, CURLOPT_POSTFIELDS, $data); 
```

it also works.

There is however a PodioError that returns no message after calling this with the above changes... Any ideas?

http://stackoverflow.com/questions/27273695/error-when-using-file-upload-method-podio-api

**Comment by stechnique** [comment] 2015-03-06 03:07
Just ran into this. Is there no way to upload using the Podio API on PHP 5.5+??

**Comment by stechnique** [comment] 2015-03-06 03:43
I went around by changing lines after 128 in lib/podio.php:

    if (!empty($options['upload'])) {
        $cfile = curl_file_create(substr($attributes[ "source" ], 1));
        // Assign POST data
        $attributes[ "source" ] = $cfile;
        curl_setopt(self::$ch, CURLOPT_POST, TRUE);
        curl_setopt(self::$ch, CURLOPT_POSTFIELDS, $attributes);
        self::$headers['Content-type'] = 'multipart/form-data';
    }

Inspired by your snippet above, but in my (older) version of the podio-php API your snippet was not working. I needed to override $attributes['source'] and not ['filename']. Also needed to strip the @ in front of the filename before creating the CurlFile.

Thanks.

**Comment by jamestrusleroval** [comment] 2015-03-06 16:01
It seems that you cannot test uploads from localhosts... You need to put it on a website that is visible to Podio... There may be a better way of doing this, but this resolved my problem

**Comment by stechnique** [comment] 2015-03-06 16:16
Ok, thanks for your input. My fix above enabled me to upload from localhost (as I always have before PHP 5.5). Also works on the production server.

**Comment by Desmaster** [comment] 2015-04-13 13:47
This worked for me, unfortunately I found this issue after about 7 hours of digging :p. 
Thanks!

**Comment by jeff-goodman** [comment] 2018-12-10 10:23
I am having trouble with this issue.  I see there is a file in PodioFile.php ([here](https://github.com/podio/podio-php/commit/d4bed5778776efe0d7b86b271244004b60087c62)).  Do I need to make a change in Podio.php for this to work as in the comments above?  I have tried both @stechnique and the original snippet (and combinations of these) and I'm still getting errors.

**Comment by jeff-goodman** [comment] 2018-12-15 21:55
The file upload to Podio used to work on my website, but it has stopped working.  I have updated PodioFile.php with the update, and it now works again on my localhost for testing but not on the webserver.  Both are running PHP 5.6.

In my PodioFile.php I have:
`public static function upload($file_path, $file_name) {
    $source = defined('PHP_MAJOR_VERSION') && PHP_MAJOR_VERSION >= 5 ? new CurlFile(realpath($file_path)) : '@'.realpath($file_path);
    return self::member(Podio::post("/file/v2/", array('source' => $source, 'filename' => $file_name), array('upload' => TRUE, 'filesize' => filesize($file_path))));
  }`
In Podio.php I have:
` if (!empty($options['upload'])) {
          curl_setopt(self::$ch, CURLOPT_POST, TRUE);
          if(!class_exists("\CURLFile") && defined('CURLOPT_SAFE_UPLOAD')) {
            curl_setopt(self::$ch, CURLOPT_SAFE_UPLOAD, FALSE);
          }
          curl_setopt(self::$ch, CURLOPT_POSTFIELDS, $attributes);
          self::$headers['Content-type'] = 'multipart/form-data';
        }`

Then in my main script I have:
`Podio::setup($client_id, $client_secret);
    Podio::authenticate_with_app($app_id, $app_token);

    $file = PodioFile::upload($filelocation, 'Signed Document.pdf');
    $upload = PodioFile::attach(intval($file->file_id), array('ref_type' => 'item', 'ref_id' => intval($item_id)));`

Any help with this would be hugely appreciated! I've spent hours trying to fix it, but can only get it to work on my localhost.

Thanks,
Jeff

**Comment by damienbdg** [comment] 2019-04-04 22:10
@jeff-goodman 
Did you find a solution? I'm facing the same issue. Getting "Connection to Podio API failed: [92]" as well.

**Comment by jeff-goodman** [comment] 2019-04-05 02:56
@damienbdg No I haven't been able to resolve this issue.

**Comment by daniel-sc** [comment] 2019-06-02 15:17
Hi @jeff-goodman, @damienbdg,

this should have been resolved with v4.4.0 - see 
* https://github.com/podio-community/podio-php/pull/119 and
* https://github.com/podio-community/podio-php/pull/109

Can you confirm this?

**Comment by damienbdg** [comment] 2019-06-07 17:49
Hey, thanks for reaching out!

I believe my issue was related to my server rather then the Podio library. Not sure what particular part of the server wasn’t compatible but I moved to an Ubuntu 18 server (from CentOS 6) and the issue is gone.

--Damien

**Closed** 2019-06-07 18:23 UTC
Labels: enhancement, question

**Comment by dilipsoni** [comment] 2019-07-26 15:24
@damienbdg , As i updated My php version 7.2.20 i got same error , Any Solution There Without Changing my server.
![Screenshot_14](https://user-images.githubusercontent.com/16918819/61962592-72cf3880-afe7-11e9-9feb-ca8ad2db1bfb.png)

**Comment by damienbdg** [comment] 2019-07-26 15:36
The 92 is a curl error. From searching around what I found is that the issue is related to HTTP/2. I tried updating my server in several ways around that idea but wasn't able to fix the issue. Eventually I just changed servers and the problem was gone. Still don't know what component was not compatible with Podio's server. Sorry about that, gl.
